name: Triggered Workflow
on: 
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
        type: string
      param2:
        description: 'Parameter 2'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use inputs
        run: |
          echo "Parameter 1: ${{ github.event.inputs.param1 }} - Parameter 2: ${{ github.event.inputs.param2 }}"
